root: true
parserOptions:
  sourceType: module
  ecmaVersion: 11
  ecmaFeatures:
    jsx: true
extends:
  - eslint:recommended
  - prettier
  - prettier/react
  - plugin:react/recommended
plugins:
  - prettier
env:
  browser: true
  node: true
rules:
  no-unused-vars:
    - error
    - varsIgnorePattern: React
  react/prop-types: 1
